### PR TITLE
Create CRUD For Flashcard Resource

### PR DESCRIPTION
**Pull request by ethaeral**
# Description

Describe change or new feature here.

CRUD functionality to flashcard resource

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ethaeral** [comment]
Still dependent on create deck - PR not actually ready

**Comment by ethaeral** [comment]
ready for review

**Review by Omulosi — COMMENTED** [review]
Everything looks ok, functionality wise but just a couple of things to consider:
* In designing routes for REST apis, you shouldn't include such words as `all` in the routes, just do:
`api/resource[cards, decks etc]/:id` e.g to get all items from a resource, just do `/api/resource/`, dont put `all` in the route. For the cards examples, say, you'd only have the following routes: `api/cards` and `api/cards/:id` then you can qualify them using http verbs get, post, put, delete etc so `get /api/cards` would retrieve all cards, `get /api/cards/:id` would retrieve a single card.
* Also, the names for resources in routes should be in plural, for example `/api/cards` instead of `api/card`
* Finally, this is a bit subjective, instead of naming yr files in the flashcards resource folder as `flashcardsMiddleware.js` etc, why not just use `middleware,js`, `routes.js` and so on? I think this would be more uniform, after all, the files are already inside a `flashcards` folder.

**Comment by ethaeral** [comment]
@Omulosi 
On the Trello board there a function to get all cards by the user - I can change the word all but there needs to be a differentiated to find all the cards in general vs all cards by the user. So just having using /:id or /:user_id will confuse the backend.

I can change it to cards

I named it that way in the case when I have multiple tabs open and I have two models open I can quickly tell which model I want to click on.

**Review by Omulosi — COMMENTED** [review]
change `/api/cards/by_user/:userId` to `/api/cards/users/:userId`

Otherwise, nice job!

**Review by Omulosi — DISMISSED** [review]
great!

In `/api/cards/**user**/:userId`,  make `user` plural, should be `users`

**Comment by ethaeral** [comment]
I dont think it should be users because its calling from one user and that's it's only purpose in the flashcard resource

**Comment by Omulosi** [comment]
> I dont think it should be users because its calling from one user and that's it's only purpose in the flashcard resource

In REST API convention, to specify a single resource, the endpoint should be in the format `resource-name/id`, in this case it is `users/:id`, then for an endpoint returning many resources, you just do `resources/` i.e. `users/` ...in either case, the resource name ought to be plural

**Review by Omulosi — DISMISSED** [review]
super

**Pull request merged**
