### PR TITLE
Create Test Suites for Signup endpoint

### PR DESCRIPTION
**Pull request by emkayDauda**
# Description

Write tests for the sign up endpoint with a coverage of at least 70%.

## Checklist

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works .
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ethaeral — COMMENTED** [review]
this error is showing: 

Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated

**Comment by emkayDauda** [comment]
Thanks for letting me know, Richany.

Apparently, I was supposed to destroy my instance of knex to stop all asynchronous operations.

More info here: https://www.donnfelker.com/fixing-jest-did-not-exit-issue/

**Review by ethaeral — APPROVED** [review]
Nice tests Maaruf. It's good to test behaviors and make sure the response you're getting is not going to change much so you don't have to change it later on. Love it.

**Review by nobioma1 — APPROVED** [review]
👍

**Pull request merged**
