### PR TITLE
fix User Delete

### PR DESCRIPTION
**Pull request by nobioma1**
# Description
- Remove multiple 'authorized' middleware on route
- Create middleware to validate password 
- Add tests

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ethaeral — DISMISSED** [review]
Looks good noble thank you!

**Review by Omulosi — COMMENTED** [review]
Did you handle the case when one user (already authorized) could potentially attempt to delete another user's account?
Otherwise great changes, nothing to add really

**Comment by nobioma1** [comment]
> Did you handle the case when one user (already authorized) could potentially attempt to delete another user's account?
> Otherwise great changes, nothing to add really

@Omulosi  Great catch!  To handle this, we won't have to pass the id of the user to be deleted as a param instead use the id of the currently logged-in user. 👍

**Comment by Omulosi** [comment]
> > Did you handle the case when one user (already authorized) could potentially attempt to delete another user's account?
> > Otherwise great changes, nothing to add really
> 
> @Omulosi Great catch! To handle this, we won't have to pass the id of the user to be deleted as a param instead use the id of the currently logged-in user.

Yeah, I believe that will work too. Thanks for the changes you've made.

**Review by Omulosi — DISMISSED** [review]
super!

**Pull request merged**
