### PR TITLE
Set Up Express Server

### PR DESCRIPTION
**Pull request by emkayDauda**
# Description
Set up Express Server returning a generic welcome message on GET request.

Implement Base Route. Add a few dependencies required for task.

## Checklist

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ethaeral — COMMENTED** [review]
Great job on setting up the server so fast!

May I suggest creating a config folder with an index file so we can keep declaring env variables in one area to keep code clean.

**Comment by emkayDauda** [comment]
I don't know what that meins or how to do it, but wouldn't we end up committing those variables?

**Comment by emkayDauda** [comment]
Thanks for the tip, @richanynguon, ended up doing the config thing...

**Review by ethaeral — APPROVED** [review]
Thank you!

**Review by nobioma1 — APPROVED** [review]

**Pull request merged**
